#!/bin/sh

GLITE_LOCATION=${GLITE_LOCATION:-/opt/glite}
GLITE_LOCATION_VAR=${GLITE_LOCATION_VAR:-$GLITE_LOCATION/var}

[ -f /etc/glite.conf ] && . /etc/glite.conf
[ -f $GLITE_LOCATION/etc/glite-wms.conf ] && . $GLITE_LOCATION/etc/glite-wms.conf

[ -f $GLITE_LOCATION/etc/lb.conf ] && . $GLITE_LOCATION/etc/lb.conf
[ -f $GLITE_LOCATION_VAR/etc/lb.conf ] && . $GLITE_LOCATION_VAR/etc/lb.conf

[ -f $HOME/.glite.conf ] && . $HOME/.glite.conf

unset creds port

start()
{
	if test -z "$GLITE_USER" ;then
		echo 'Error: GLITE_USER is not set'
		echo FAILED
		return 1
	fi

	[ -n "$GLITE_HOST_CERT" -a -n "$GLITE_HOST_KEY" ] &&
		creds="-c $GLITE_HOST_CERT -k $GLITE_HOST_KEY"

	if test -z "$creds"; then
		if su - $GLITE_USER -c "test -r /etc/grid-security/hostkey.pem -a -r /etc/grid-security/hostcert.pem"; then
			echo "$0: WARNING: /etc/grid-security/hostkey.pem readable by $GLITE_USER"
			creds="-c /etc/grid-security/hostcert.pem -k /etc/grid-security/hostkey.pem"
		fi
	fi

	[ -z "$creds" ] && echo $0: WARNING: No credentials specified. Using default lookup which is dangerous. >&2

	[ -n "$GLITE_LB_LOGGER_PORT" ] && port="--port $GLITE_LB_LOGGER_PORT"
	[ -n "$GLITE_LB_IL_SOCK" ] && sock="--socket $GLITE_LB_IL_SOCK"
	[ -n "$GLITE_LB_IL_FPREFIX" ] && fprefix="--file-prefix $GLITE_LB_IL_FPREFIX"

	mkdir -p /var/glite/log 
	chown $GLITE_USER /var/glite/log
	echo -n Starting glite-lb-logd ...
        (cd /tmp && ls -f /tmp |grep ^dglogd_sock_ |xargs rm -f)
	su - $GLITE_USER -c "$GLITE_LOCATION/bin/glite-lb-logd \
		$creds $port $sock $fprefix" && echo " done" || echo " FAILED"

	echo -n Starting glite-lb-interlogd ...
	su - $GLITE_USER -c "$GLITE_LOCATION/bin/glite-lb-interlogd \
		$creds $sock $fprefix" && echo " done" || echo " FAILED"
}

stop()
{
		echo -n Stopping glite-lb-logd ...
		killall glite-lb-logd
		echo " done"
		echo -n Stopping glite-lb-interlogd ...
		killall glite-lb-interlogd
		echo " done"
}

status()
{
	LC_ALL=C
	if netstat -an --inet | grep "^tcp .* 0.0.0.0:${GLITE_LB_LOGGER_PORT:-9002} .*LISTEN" >/dev/null 2>&1 ;then
	echo glite-lb-logd running
	else
	echo glite-lb-logd not running
	return 1
	fi
	if netstat -an --unix | grep "^unix .* LISTEN.* ${GLITE_LB_IL_SOCK:-/tmp/interlogger.sock}$" >/dev/null 2>&1 ;then
	echo glite-lb-interlogd running
	else
	echo glite-lb-interlogd not running
	return 1
	fi
}

case x$1 in
	xstart)	start;;
	xstop)	stop;;
	xrestart) stop; start;;
	xstatus) status;;
	x*)	echo usage: $0 start,stop,restart,status >&2
		exit 1;;
esac
