.TH GLITE-LB-LOAD 8 "April 2008" "EGEE Project" "Logging&Bookkeeping"

.SH NAME
glite-lb-load - utility for loading job events into the L&B database

.SH SYNOPSIS
.B glite-lb-load
.RI [ options ]
.br

.SH DESCRIPTION
.B glite-lb-load 
is utility for loading job events into the L&B database. It is primarilly used for recovery purposes. By default, it loads events from the last dump.

.SH OPTIONS
.IP "\-m, --server \fIbkserver\fR"
L&B server machine name. If not specified, the environment variable EDG_WL_QUERY_SERVER is beeing checked.

.IP "\-f, --file \fIfilename\fR"
File with dumped data to be loaded.

.IP "\-h, --help"
Display help.

.IP "\-v, --version"
Display version.

.IP "\-d, --debug"
Print diagnostics on the 
.I stderr\fR.\fP

.\".SH USAGE
.\" Add any additional description here

.PP

.SH FILES
No configuration files needed.

.SH ENVIRONMENT
No environment variables needed.

.SH REPORTING BUGS
Please, report all bugs to EGEE Bug Tracking System located at https://savannah.cern.ch

.SH SEE ALSO
.B glite-lb-bkindex\fR(8),\fP glite-lb-bkserverd\fR(8),\fP glite-lb-dump\fR(8),\fP glite-lb-purge\fR(8),\fP

.SH AUTHOR
EU EGEE, JRA1.
