.TH GLITE-LB-MON 1 "Mar 2006" "EU EGEE Project" "Logging & Bookkeeping Utils"

.SH NAME
glite-lb-mon - program for monitoring the number of jobs on the LB server and their several statistics

.SH SYNOPSIS
.B glite-lb-mon
.B [-t time -h]
.br

.SH DESCRIPTION
.B glite-lb-mon
is a low-level program for monitoring the the number of jobs on the LB server and their several statistics.
Values like minimum, average and maximum time spent in the system are calulated for jobs that entered 
the final state (Aborted, Cleared, Cancelled) in specific time (default last hour). Also number of jobs
that entered the system during this time is calculated.

.SH OPTIONS
.TP
.B \-t time, \-\-time=time
Querying time in seconds from now to the past [deault 3600].

.TP
.B \-h, \-\-help
Display help and exit.

.SH ENVIRONMENT
.TP
.B EDG_WL_QUERY_SERVER
set this environment variable to specify the LB server address to query

.SH FILES
A special bkindex configuration needed. The following time indices must be defined:

.nf
	[ type = "time"; name = "submitted" ],
	[ type = "time"; name = "cleared" ],
	[ type = "time"; name = "aborted" ],
	[ type = "time"; name = "cancelled" ],
.fi


.SH BUGS
Please report all bugs to CESNET gLite L&B issue tracker available at
.I https://github.com/CESNET/glite-lb/issues

.SH SEE ALSO
.BR glite-lb-bkindex (8), 
.BR glite-lb-mon (1)

.SH AUTHOR
EU EGEE JRA1, CESNET group.
