#!/bin/sh
set -e

getent group glite >/dev/null || groupadd -r glite
getent passwd glite >/dev/null || useradd -r -g glite -d /var/lib/glite -c "gLite user" glite
mkdir -p /var/lib/glite /var/log/glite /var/run/glite /var/spool/glite/lb-locallogger /var/spool/glite/lb-notif /var/spool/glite/lb-proxy 2>/dev/null || :
chown -R glite:glite /var/lib/glite /var/log/glite /var/run/glite /var/spool/glite/lb-locallogger /var/spool/glite/lb-notif /var/spool/glite/lb-proxy

#DEBHELPER#
