# Makefile for LaTeX, EGEE-JRA1-Testplan

DOCUMENT=api
DELIVERY=TEMPLATE-$(VERSION)
SRC=.
STYLEPATH := $(SRC)/../../../org.glite.templates-latex-style
VERSION=`cat $(SRC)/VERSION`

include $(STYLEPATH)/Makefile.template
