.TH GLITE-LB-MON-DB 1 "Mar 2006" "EU EGEE Project" "Logging & Bookkeeping Utils"

.SH NAME
glite-lb-mon-db - program for monitoring the number of jobs in the LB system

.SH SYNOPSIS
.B glite-lb-mon-db
.B [-m dbstring -d -v -h]
.br

.SH DESCRIPTION
.B glite-lb-mon-db
is a low-level program for monitoring the the number of jobs in the LB system. 
Using the LB internals, it connects directly to the underlying MySQL database and reads
the number of jobs in each state.

.SH OPTIONS
.TP
.B \-m dbstring, \-\-mysql=dbstring
Use non-default database connection string.

.TP
.B \-d, \-\-debug
Print debug info (if any).

.TP
.B \-v, \-\-verbose
Be verbose.

.TP
.B \-h, \-\-help
Display help and exit.

.SH EXAMPLES
.TP 
.BI glite-lb-mon-db 
this is the default usage
.TP
.BI glite-lb-mon-db \ -m \ lbserver/@localhost:lbproxy
use this dbstring to query the LB Proxy database. WARNING: the data in the LB Proxy may be incomplete!

.SH ENVIRONMENT
.TP
.B MYSQL_UNIX_PORT
set this environment variable to specify the path to the non-default MySQL socket path
.TP
.B LBDB
you can set this environment variable as an alternative to specify the non-default database connection string

.SH BUGS
Please report all bugs to CESNET gLite L&B issue tracker available at
.I https://github.com/CESNET/glite-lb/issues

.SH SEE ALSO
.BR glite-lb-mon (1)

.SH AUTHOR
EU EGEE JRA1, CESNET group.
