.TH GLITE-LB-DUMP 8 "April 2008" "EGEE Project" "Logging&Bookkeeping"

.SH NAME
glite-lb-dump - utility for dumping job events from L&B database

.SH SYNOPSIS
.B glite-lb-dump
.RI [ options ]
.br

.SH DESCRIPTION
.B glite-lb-dump 
is utility for dumping job events from L&B database. It is primarilly used for statistical purposes. By default, it dumps events from the time when the last dum ended upto now. 

.B glite-lb-dump 
may be run periodically, however the periodic dumps are done by server itself, so check the configuration of the server first.

.SH OPTIONS
.TP
.BI \-m \fR,\fP --server mkserver
L&B server machine name. If not specified, the environment variable EDG_WL_QUERY_SERVER is beeing checked.

.TP
.BI \-f \fR,\fP --from YYYYMMDDHHmmss 
Beginning of the time interval for events to be dumped.

.TP
.BI \-t \fR,\fP --to YYYYMMDDHHmmss
End of the time interval for events to be dumped.

.TP
.BI \-h \fR,\fP --help
Display help.

.TP
.BI \-v \fR,\fP --version
Display version.

.TP
.B "-d\fR,\fP --debug"
Print diagnostics on the 
.I stderr\fR.\fP

.\".SH USAGE
.\" Add any additional description here

.PP

.SH FILES
No configuration files needed.

.SH ENVIRONMENT
No environment variables needed.

.SH REPORTING BUGS
Please, report all bugs to EGEE Bug Tracking System located at https://savannah.cern.ch

.SH SEE ALSO
.B glite-lb-bkindex\fR(8),\fP glite-lb-bkserverd\fR(8),\fP glite-lb-interlogd\fR(8),\fP glite-lb-logd\fR(8),\fP glite-lb-logevent\fR(1),\fP

.SH AUTHOR
EU EGEE, JRA1.
