.TH GLITE-LB-LOGEVENT 1 "April 2008" "EU EGEE Project" "Logging&Bookkeeping"

.SH NAME
glite-lb-logevent - program for logging events to L&B subsystem

.SH SYNOPSIS
.B glite-lb-logevent
.B -s Application  -e UserTag
.B -j
.I JOBID 
.B -c
.I SEQCODE 
.B --name 
.I NAME
.B --value
.I VALUE
.br

.SH DESCRIPTION
.B glite-lb-logevent 
is a low-level program for logging events to the L&B service.
It is used internally by WMS components and has many more options, that are not recomend to be used at the user level.
At the user level it is supposed to be used only for logging user tag events.

.SH USAGE
Besides
.I NAME
and
.I VALUE
of the tag, which are user defined, the user has to specify a valid
.I JOBID\fR,\fP
and
.I SEQCODE
(L&B event sequence code).

The user application is always executed from within a 
.I JobWrapper
script. The wrapper sets the appropriate JobId in the environment variable
EDG_WL_JOBID. The user should pass this value to the \-j option of
.B glite-lb-logevent.

Similarly, the wrapper sets an initial value of the event sequence code
in the environment variable EDG_WL_SEQUENCE_CODE.
If the user application calls 
.B glite-lb-logevent
just once, it is sufficient to pass this value to the \-c option.
However, if there are more subsequent calls, the user is responsible for
capturing an updated sequence code from the 
.B stdout
of 
.B glite-lb-logevent
and using it in subsequent calls.
The L&B design requires the sequence codes in order to be able to sort
events correctly while not relying on strictly synchronized clocks.

.SH EXAMPLE
The example bellow is a job consisting of 100 phases.
A user tag
.I phase
is used to log the phase currently being executed.
Subsequently, the user may monitor execution of the job phases
as a part of the job status returned by L&B.

.nf
#!/bin/sh

for p in `seq 1 100`; do

	# log the UserTag event
	EDG_WL_SEQUENCE_CODE=`glite-lb-logevent \-s Application
		\-e UserTag
		\-j $EDG_WL_JOBID \-c $EDG_WL_SEQUENCE_CODE
		\-\-name=phase \-\-value=$p`

	# do the actual computation here
done

.fi



.SH OTHER OPTIONS
See command line help (glite-lb-logevent \-h) for extensive help on all options.
However, EDG users should should follow the usage shown in SYNOPSIS strictly.
Logging other events may confuse the L&B service and cause wrong job status
information to be reported.

.SH FILES
No configuration files needed.

.SH REPORTING BUGS
Please, report all bugs to EU EGEE Bug Tracking System located at https://savannah.cern.ch

.SH SEE ALSO
.B glite-lb-bkserverd\fR(8),\fP glite-lb-interlogd\fR(8),\fP glite-lb-logd\fR(8)

.SH AUTHOR
EU EGEE, JRA1.
