#!/bin/bash

TEST_SCRIPT=/home/mulac/src/ORG/org.glite.lb.client/src/perftest_jobreg.sh

db_clean() {
	mysql -u lbserver -e "delete from users;" lbserver20_test
	mysql -u lbserver -e "delete from status_tags;" lbserver20_test
	mysql -u lbserver -e "delete from states;" lbserver20_test
	mysql -u lbserver -e "delete from short_fields;" lbserver20_test
	mysql -u lbserver -e "delete from jobs;" lbserver20_test
	mysql -u lbserver -e "delete from events;" lbserver20_test
	mysql -u lbserver -e "delete from server_state;" lbserver20_test
	mysql -u lbserver -e "delete from notif_registrations;" lbserver20_test
	mysql -u lbserver -e "delete from notif_jobs;" lbserver20_test
	mysql -u lbserver -e "delete from long_fields;" lbserver20_test
	mysql -u lbserver -e "delete from acls;" lbserver20_test
}


#db_clean;
GLITE_LOCATION=/home/mulac/src/ORG.LB_BUF_LB_DAG_EMBRIONIC/stage
#killall -9 glite-lb-bkserverd
LB_BUF_BYTES=0
LB_BUF_LINES=10
$TEST_SCRIPT  1>>/tmp/test_ORG.LB_BUF_LB_DAG_EMBRIONIC_10 2>>/tmp/test_ORG.LB_BUF_LB_DAG_EMBRIONIC_10

exit(0);

db_clean;
GLITE_LOCATION=/home/mulac/src/ORG/stage
#for i in `seq 1 30`; do $TEST_SCRIPT ; done 2>>/tmp/test_ORG 1>>/tmp/test_ORG
killall -9 glite-lb-bkserverd
$TEST_SCRIPT &>/tmp/test_ORG

db_clean;
GLITE_LOCATION=/home/mulac/src/ORG.LB_BUF/stage
#for i in `seq 1 30`; do $TEST_SCRIPT ; done &>/tmp/test_ORG.LB_BUF
killall -9 glite-lb-bkserverd
$TEST_SCRIPT &>/tmp/test_ORG.LB_BUF

db_clean;
GLITE_LOCATION=/home/mulac/src/ORG.LB_DAG_EMBRIONIC/stage
#for i in `seq 1 30`; do $TEST_SCRIPT ; done &>/tmp/test_ORG.LB_DAG_EMBRIONIC
killall -9 glite-lb-bkserverd
$TEST_SCRIPT &>/tmp/test_ORG.LB_DAG_EMBRIONIC

db_clean;
GLITE_LOCATION=/home/mulac/src/ORG.LB_BUF_LB_DAG_EMBRIONIC/stage
#for i in `seq 1 30`; do $TEST_SCRIPT; done &>/tmp/test_ORG.LB_BUF_LB_DAG_EMBRIONIC
unset LB_BUF_BYTES
unset LB_BUF_LINES
killall -9 glite-lb-bkserverd
$TEST_SCRIPT &>/tmp/test_ORG.LB_BUF_LB_DAG_EMBRIONIC

db_clean;
GLITE_LOCATION=/home/mulac/src/ORG.LB_BUF_LB_DAG_EMBRIONIC/stage
killall -9 glite-lb-bkserverd
LB_BUF_BYTES=0
LB_BUF_LINES=5
$TEST_SCRIPT &>/tmp/test_ORG.LB_BUF_LB_DAG_EMBRIONIC_5

db_clean;
GLITE_LOCATION=/home/mulac/src/ORG.LB_BUF_LB_DAG_EMBRIONIC/stage
killall -9 glite-lb-bkserverd
LB_BUF_BYTES=0
LB_BUF_LINES=20
$TEST_SCRIPT &>/tmp/test_ORG.LB_BUF_LB_DAG_EMBRIONIC_20


db_clean;
GLITE_LOCATION=/home/mulac/src/ORG.LB_BUF_LB_DAG_EMBRIONIC/stage
killall -9 glite-lb-bkserverd
LB_BUF_BYTES=0
LB_BUF_LINES=100
$TEST_SCRIPT &>/tmp/test_ORG.LB_BUF_LB_DAG_EMBRIONIC_100


db_clean;
GLITE_LOCATION=/home/mulac/src/ORG.LB_BUF_LB_DAG_EMBRIONIC/stage
killall -9 glite-lb-bkserverd
LB_BUF_BYTES=0
LB_BUF_LINES=500
$TEST_SCRIPT &>/tmp/test_ORG.LB_BUF_LB_DAG_EMBRIONIC_500


db_clean;
GLITE_LOCATION=/home/mulac/src/ORG.LB_BUF_LB_DAG_EMBRIONIC/stage
killall -9 glite-lb-bkserverd
LB_BUF_BYTES=0
LB_BUF_LINES=100
$TEST_SCRIPT &>/tmp/test_ORG.LB_BUF_LB_DAG_EMBRIONIC_1000


exit 0;

