top_srcdir=..
stagedir=.
package=glite-lb-emi-lb
version=0.0.0
PREFIX=/opt/glite
prefix=

-include Makefile.inc
-include ${top_srcdir}/project/version.properties

default all:

install:

stage:
	$(MAKE) install PREFIX=${stagedir}

check:

clean:

distclean:
	rm -rvf project/changelog Makefile.inc *.spec debian/

.PHONY: default all check install stage clean distclean
